### PR TITLE
Remove dependencies

### PR DESCRIPTION
**Pull request by dohomi**
This is the code I am using right now. Works flawlessly.

This could be applied to the useGoogleForm hook as well and then the dependency could be removed.

Let the user decide which fetch fallback they would like to use.

### CODE REVIEW

**Comment by francisconeves97** [comment]
Hey @dohomi! That contribution looks great 🙏 

There were only a few problems running the unit tests.

Since that script is meant to run on the server side wouldn't we need to add the `node-fetch` dependency first? I think we might have to split the lib into client/server side before doing this change, not sure if adding the `node-fetch` dependency will mess up the build

**Comment by dohomi** [comment]
@francisconeves97 just use `isomorphic-unfetch` like its described here:
https://www.npmjs.com/package/isomorphic-unfetch#usage

**Comment by dohomi** [comment]
The idea is, that both client and server will use this function. so you can import it as well inside of the userGoogleForm hook

**Comment by dohomi** [comment]
#11 is a better PR

**Pull request closed without merging**
